import { sveltekit } from '@sveltejs/kit/vite';
import { svelteTesting } from '@testing-library/svelte/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit(), svelteTesting()],
	test: {
		environment: 'jsdom',
		setupFiles: ['./src/test/setup.js'],
		include: ['src/**/*.{test,spec}.js'],
		coverage: {
			provider: 'v8',
			reporter: ['text', 'json-summary', 'html'],
			// V8 reports branches generated by the Svelte compiler rather than only
			// branches authored in component source. Component behaviour stays covered
			// by the Testing Library suites; percentage enforcement targets authored JS.
			include: ['src/**/*.js'],
			exclude: [
				'src/**/*.{test,spec}.js',
				'src/test/**',
				// This static SvelteKit mode export has no runtime behaviour to exercise.
				'src/routes/+layout.js',
				'src/routes/pbl/**/+page.js',
				'src/app.d.ts',
				'src/app.html',
				'src/service-worker.js'
			],
			thresholds: {
				lines: 100,
				branches: 100,
				functions: 100,
				statements: 100
			}
		}
	}
});
